// Generated by gencpp from file my_robot_msgs/LightLedRequest.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_LIGHTLEDREQUEST_H
#define MY_ROBOT_MSGS_MESSAGE_LIGHTLEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct LightLedRequest_
{
  typedef LightLedRequest_<ContainerAllocator> Type;

  LightLedRequest_()
    : led_number(0)
    , led_state(0)  {
    }
  LightLedRequest_(const ContainerAllocator& _alloc)
    : led_number(0)
    , led_state(0)  {
  (void)_alloc;
    }



   typedef int64_t _led_number_type;
  _led_number_type led_number;

   typedef int64_t _led_state_type;
  _led_state_type led_state;





  typedef boost::shared_ptr< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LightLedRequest_

typedef ::my_robot_msgs::LightLedRequest_<std::allocator<void> > LightLedRequest;

typedef boost::shared_ptr< ::my_robot_msgs::LightLedRequest > LightLedRequestPtr;
typedef boost::shared_ptr< ::my_robot_msgs::LightLedRequest const> LightLedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::LightLedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::LightLedRequest_<ContainerAllocator1> & lhs, const ::my_robot_msgs::LightLedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.led_number == rhs.led_number &&
    lhs.led_state == rhs.led_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::LightLedRequest_<ContainerAllocator1> & lhs, const ::my_robot_msgs::LightLedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69d6d4f2a9aaf048565b116d58bf8680";
  }

  static const char* value(const ::my_robot_msgs::LightLedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69d6d4f2a9aaf048ULL;
  static const uint64_t static_value2 = 0x565b116d58bf8680ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/LightLedRequest";
  }

  static const char* value(const ::my_robot_msgs::LightLedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"int64 led_number\n"
"int64 led_state\n"
;
  }

  static const char* value(const ::my_robot_msgs::LightLedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.led_number);
      stream.next(m.led_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightLedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::LightLedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::LightLedRequest_<ContainerAllocator>& v)
  {
    s << indent << "led_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.led_number);
    s << indent << "led_state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.led_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_LIGHTLEDREQUEST_H
